import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, afterEach, it, expect, vi } from "vitest";
import { FeedbackDialog } from "./FeedbackDialog";
import { submitFeedback } from "../services/productSupport";
vi.mock("../services/productSupport", async original => ({...await original<object>(),submitFeedback:vi.fn()}));
beforeEach(() => vi.clearAllMocks());
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
async function preview() { await userEvent.type(screen.getByLabelText("제목"),"제목"); await userEvent.type(screen.getByLabelText("내용"),"입력 내용"); await userEvent.click(screen.getByRole("button",{name:"전송 정보 미리보기"})); }
it("previews only consented data and states browser fallback accurately", async () => { vi.mocked(submitFeedback).mockResolvedValue("browser"); render(<FeedbackDialog diagnostics={{platform:"desktop"}} onClose={vi.fn()} />); await preview(); expect(screen.getByText(/다음 정보가 전송됩니다/)).toBeTruthy(); expect(screen.getByText(/"platform": "desktop"/)).toBeTruthy(); expect(screen.queryByText(/"diagnostics"/)).toBeNull(); await userEvent.click(screen.getByRole("button",{name:"전송 / GitHub 작성 화면 열기"})); expect(await screen.findByText(/GitHub 작성 화면을 열었습니다/)).toBeTruthy(); });
it("keeps the draft on failure and allows retry and edit", async () => { vi.mocked(submitFeedback).mockRejectedValue(new Error("private-error")); render(<FeedbackDialog diagnostics={{}} onClose={vi.fn()} />); await preview(); await userEvent.click(screen.getByRole("button",{name:"전송 / GitHub 작성 화면 열기"})); await screen.findByText("피드백을 전송하지 못했습니다."); expect(screen.getByRole("button",{name:"다시 시도"})).toBeTruthy(); await userEvent.click(screen.getByRole("button",{name:"수정"})); expect(screen.getByLabelText("내용")).toHaveProperty("value","입력 내용"); expect(screen.queryByText("private-error")).toBeNull(); });
it("acknowledges direct submission success", async () => { vi.mocked(submitFeedback).mockResolvedValue("sent"); render(<FeedbackDialog diagnostics={{}} onClose={vi.fn()} />); await preview(); await userEvent.click(screen.getByRole("button",{name:"전송 / GitHub 작성 화면 열기"})); expect(await screen.findByText("고마워요. 피드백이 전송되었습니다.")).toBeTruthy(); });

it("shows opt-in diagnostics in preview and can retry successfully after failure", async () => { vi.mocked(submitFeedback).mockRejectedValueOnce(new Error("network-private")).mockResolvedValueOnce("sent"); render(<FeedbackDialog diagnostics={{os_version:"15.7",provider:"groq"}} onClose={vi.fn()} />); expect(screen.getByRole("checkbox")).toHaveProperty("checked",false); await userEvent.click(screen.getByRole("checkbox")); await preview(); expect(screen.getByText(/"osVersion": "15.7"/)).toBeTruthy(); await userEvent.click(screen.getByRole("button",{name:"전송 \/ GitHub 작성 화면 열기"})); await userEvent.click(await screen.findByRole("button",{name:"다시 시도"})); expect(await screen.findByText("고마워요. 피드백이 전송되었습니다.")).toBeTruthy(); });

it.each(["http","network","malformed"])("configured %s failure preserves input and retry succeeds through the real service",async kind=>{
 const real=await vi.importActual<typeof import("../services/productSupport")>("../services/productSupport"); vi.mocked(submitFeedback).mockImplementation(real.submitFeedback);vi.stubEnv("VITE_MINDCORE_FEEDBACK_ENDPOINT","https://example.com/feedback");
 const fetch=vi.fn();if(kind==="network")fetch.mockRejectedValueOnce(new TypeError("private-network"));else fetch.mockResolvedValueOnce(new Response(kind==="malformed"?'{"ok":false}':'{"ok":true}',{status:kind==="http"?500:200,headers:{"Content-Type":"application/json"}}));fetch.mockResolvedValueOnce(new Response('{"ok":true}',{status:202,headers:{"Content-Type":"application/json"}}));vi.stubGlobal("fetch",fetch);
 render(<FeedbackDialog diagnostics={{}} onClose={vi.fn()} />);await preview();expect(screen.queryByText(/아직 구성되지 않았습니다/)).toBeNull();await userEvent.click(screen.getByRole("button",{name:"피드백 보내기"}));await userEvent.click(await screen.findByRole("button",{name:"다시 시도"}));expect(await screen.findByText("고마워요. 피드백이 전송되었습니다.")).toBeTruthy();expect(fetch).toHaveBeenCalledTimes(2);await userEvent.click(screen.getByRole("button",{name:"수정"}));expect(screen.getByLabelText("내용")).toHaveProperty("value","입력 내용");
});
