import { useState } from "react";
import { feedbackEndpoint, feedbackPayload, submitFeedback, type Diagnostics, type FeedbackPayload } from "../services/productSupport";
export function FeedbackDialog({ diagnostics, onClose }: { diagnostics: Diagnostics; onClose: () => void }) {
  const [category, setCategory] = useState("버그"), [title, setTitle] = useState(""), [message, setMessage] = useState("");
  const [include, setInclude] = useState(false), [preview, setPreview] = useState<FeedbackPayload | null>(null), [busy, setBusy] = useState(false), [status, setStatus] = useState("");
  const review = () => { try { setPreview(feedbackPayload(category, title, message, include, diagnostics)); setStatus(""); } catch { setStatus("제목과 내용을 입력해 주세요."); } };
  const submit = async () => { if (!preview || busy) return; setBusy(true); try { const result = await submitFeedback(preview); setStatus(result === "sent" ? "고마워요. 피드백이 전송되었습니다." : "GitHub 작성 화면을 열었습니다. 브라우저에서 확인 후 제출해 주세요."); } catch { setStatus("피드백을 전송하지 못했습니다."); } finally { setBusy(false); } };
  return <div className="product-modal-backdrop"><section role="dialog" aria-modal="true" aria-label="피드백" className="product-modal"><h2>피드백</h2><p>MindCore 개발자에게 피드백을 보냅니다.</p><p>API key, DB token, 대화 내용은 자동으로 포함되지 않습니다.</p>{!preview ? <><label>분류<select aria-label="분류" value={category} onChange={event => setCategory(event.target.value)}>{["버그", "기능 제안", "사용성/UI", "기타"].map(value => <option key={value}>{value}</option>)}</select></label><label>제목<input maxLength={160} value={title} onChange={event => setTitle(event.target.value)} /></label><label>내용<textarea rows={6} maxLength={6000} value={message} onChange={event => setMessage(event.target.value)} /></label><label><input type="checkbox" checked={include} onChange={event => setInclude(event.target.checked)} />기본 진단 정보 포함</label><button onClick={review}>전송 정보 미리보기</button></> : <><h3>다음 정보가 전송됩니다</h3><pre className="feedback-preview">{JSON.stringify(preview, null, 2)}</pre>{!feedbackEndpoint() && <p>직접 피드백 전송이 아직 구성되지 않았습니다. GitHub 작성 화면에서 확인 후 제출해 주세요.</p>}<button disabled={busy} onClick={() => setPreview(null)}>수정</button><button disabled={busy} onClick={() => void submit()}>{busy ? "처리 중…" : status === "피드백을 전송하지 못했습니다." ? "다시 시도" : feedbackEndpoint() ? "피드백 보내기" : "전송 / GitHub 작성 화면 열기"}</button></>}{status && <p role="status">{status}</p>}<div className="product-modal-actions"><button disabled={busy} onClick={onClose}>닫기</button></div></section></div>;
}
