import { useEffect, useMemo, useRef, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { defaultProviderModels, emptyProviderValues, falseProviderValues, PROVIDERS, providerDefinition, type Provider } from "../providerConfig";

type Draft = { database_url: string; database_auth_token: string; llm_provider: Provider; user_display_name: string; persona_display_name: string; preserve_database_auth_token: boolean; preserve_identity: boolean };
type ProviderDraft = { models: Record<Provider, string>; apiKeys: Record<Provider, string>; preserveKeys: Record<Provider, boolean> };
type Validation = "untested" | "testing" | "valid" | "invalid";
type ConfigMetadata = { database_url: string; llm_provider: Provider; user_display_name: string; persona_display_name: string; turso_token_configured: boolean; provider_models: Record<Provider, string>; provider_key_configured: Record<Provider, boolean> };

const initial: Draft = { database_url: "", database_auth_token: "", llm_provider: "gemini", user_display_name: "", persona_display_name: "", preserve_database_auth_token: false, preserve_identity: false };
const initialProviders = (): ProviderDraft => ({ models: defaultProviderModels(), apiKeys: emptyProviderValues(), preserveKeys: falseProviderValues() });
const personaValid = (name: string) => name.trim().length > 0 && [...name].length <= 80 && ![...name].some((char) => { const code = char.codePointAt(0) ?? 0; return code < 32 || code === 127; });
const userNameValid = (name: string) => name.trim().length > 0 && [...name].length <= 80 && ![...name].some((char) => { const code = char.codePointAt(0) ?? 0; return code < 32 || (code >= 127 && code <= 159); });
const modelValid = (model: string) => model.trim().length > 0 && [...model].length <= 200 && ![...model].some((char) => { const code = char.codePointAt(0) ?? 0; return code < 32 || code === 127; });

export function SetupWizard({ onComplete, reconfigure = false }: { onComplete: () => void; reconfigure?: boolean }) {
  const [step, setStep] = useState(0); const [draft, setDraft] = useState<Draft>(initial); const [providerDraft, setProviderDraft] = useState<ProviderDraft>(initialProviders); const [identity, setIdentity] = useState(""); const [status, setStatus] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const [databaseValidation, setDatabaseValidation] = useState<Validation>("untested"); const [llmValidation, setLlmValidation] = useState<Validation>("untested");
  const activeModel = providerDraft.models[draft.llm_provider]; const activeApiKey = providerDraft.apiKeys[draft.llm_provider]; const preserveActiveKey = providerDraft.preserveKeys[draft.llm_provider];
  const actionDraft = useMemo(() => ({ ...draft, llm_model: activeModel, api_key: activeApiKey, preserve_api_key: preserveActiveKey, provider_models: providerDraft.models, provider_api_keys: providerDraft.apiKeys, provider_preserve_keys: providerDraft.preserveKeys }), [activeApiKey, activeModel, draft, preserveActiveKey, providerDraft]);
  const databaseSnapshot = useRef(""); const llmSnapshot = useRef("");
  const dbFingerprint = useMemo(() => `${draft.database_url}\u0000${draft.database_auth_token}\u0000${draft.preserve_database_auth_token}`, [draft.database_url, draft.database_auth_token, draft.preserve_database_auth_token]);
  const llmFingerprint = useMemo(() => `${draft.llm_provider}\u0000${activeModel}\u0000${activeApiKey}\u0000${preserveActiveKey}`, [activeApiKey, activeModel, draft.llm_provider, preserveActiveKey]);
  const currentDatabaseFingerprint = useRef(dbFingerprint); const currentLlmFingerprint = useRef(llmFingerprint); currentDatabaseFingerprint.current = dbFingerprint; currentLlmFingerprint.current = llmFingerprint;
  const dbReady = databaseValidation === "valid" && databaseSnapshot.current === dbFingerprint; const llmReady = llmValidation === "valid" && llmSnapshot.current === llmFingerprint;
  const update = (key: keyof Draft, value: string) => setDraft((current) => ({ ...current, [key]: value })); const previous = () => { setStatus(null); setStep((current) => Math.max(0, current - 1)); };
  const updateProviderValue = (field: "models" | "apiKeys", value: string) => setProviderDraft((current) => ({ ...current, [field]: { ...current[field], [draft.llm_provider]: value }, ...(field === "apiKeys" ? { preserveKeys: { ...current.preserveKeys, [draft.llm_provider]: false } } : {}) }));

  useEffect(() => { if (!reconfigure) return; void invoke<ConfigMetadata>("get_config_metadata").then((meta) => { const models = { ...defaultProviderModels(), ...meta.provider_models }; const preserveKeys = { ...falseProviderValues(), ...meta.provider_key_configured }; const next = { ...initial, database_url: meta.database_url, llm_provider: meta.llm_provider, user_display_name: meta.user_display_name || "User", persona_display_name: meta.persona_display_name, preserve_database_auth_token: meta.turso_token_configured, preserve_identity: true }; setDraft(next); setProviderDraft({ models, apiKeys: emptyProviderValues(), preserveKeys }); databaseSnapshot.current = `${next.database_url}\u0000\u0000${next.preserve_database_auth_token}`; llmSnapshot.current = `${next.llm_provider}\u0000${models[next.llm_provider]}\u0000\u0000${preserveKeys[next.llm_provider]}`; setDatabaseValidation("valid"); setLlmValidation("valid"); }).catch(() => setStatus("Could not load the existing MindCore configuration.")); }, [reconfigure]);
  useEffect(() => { if (step === 3 && !identity && !reconfigure) void invoke<string>("generic_identity_template").then(setIdentity).catch(() => setStatus("Could not load the generic identity template.")); }, [identity, reconfigure, step]);
  useEffect(() => { if (databaseSnapshot.current !== dbFingerprint) { databaseSnapshot.current = ""; setDatabaseValidation("untested"); } }, [dbFingerprint]);
  useEffect(() => { if (llmSnapshot.current !== llmFingerprint) { llmSnapshot.current = ""; setLlmValidation("untested"); } }, [llmFingerprint]);
  const test = async (action: "database" | "llm") => { if (busy) return; const snapshot = action === "database" ? dbFingerprint : llmFingerprint; if (action === "database") setDatabaseValidation("testing"); else setLlmValidation("testing"); setBusy(true); setStatus(null); try { await invoke("run_setup_action", { action, draft: actionDraft }); const current = action === "database" ? currentDatabaseFingerprint.current : currentLlmFingerprint.current; if (current !== snapshot) return; if (action === "database") { databaseSnapshot.current = snapshot; setDatabaseValidation("valid"); } else { llmSnapshot.current = snapshot; setLlmValidation("valid"); } setStatus("Connected"); } catch { const current = action === "database" ? currentDatabaseFingerprint.current : currentLlmFingerprint.current; if (current === snapshot) { if (action === "database") setDatabaseValidation("invalid"); else setLlmValidation("invalid"); setStatus(action === "database" ? "Could not connect to Turso. Check the database URL and token." : `Could not connect to ${providerDefinition(draft.llm_provider).label}. Check the API key and model ID.`); } } finally { setBusy(false); } };
  const initialize = async () => { setBusy(true); setStatus(null); try { const state = await invoke<string>("run_setup_action", { action: "classify", draft: actionDraft }); if (state === "PARTIAL_OR_UNKNOWN") { setStatus("This database contains an incomplete or unsupported MindCore schema. It will not be overwritten."); return; } await invoke("run_setup_action", { action: "initialize", draft: actionDraft }); await invoke("save_mindcore_config", { draft: actionDraft, identity }); await invoke("start_mindcore_backend"); onComplete(); } catch { setStatus("MindCore could not initialize this configuration. Your existing configuration was not changed."); } finally { setBusy(false); } };
  const navigation = (enabled: boolean) => <div className="setup-navigation"><button className="login-button" onClick={previous}>Back</button><button className="login-button" disabled={!enabled || busy} onClick={() => { setStatus(null); setStep((current) => current + 1); }}>Continue</button></div>;
  return <main className="login-screen"><div className="login-form setup-wizard"><div className="login-title">MINDCORE</div>
    {step === 0 && <><h1>{reconfigure ? "Reconfigure MindCore" : "Welcome to MindCore"}</h1><p>MindCore needs a database, a language model provider, and a Persona before first use.</p><button className="login-button" onClick={() => setStep(1)}>{reconfigure ? "Edit configuration" : "Get Started"}</button></>}
    {step === 1 && <><h1>Database Setup</h1><input placeholder="Turso Database URL" value={draft.database_url} onChange={(event) => update("database_url", event.target.value)} /><input type="password" placeholder={draft.preserve_database_auth_token ? "Configured — leave blank to keep" : "Turso Auth Token"} value={draft.database_auth_token} onChange={(event) => setDraft((current) => ({ ...current, database_auth_token: event.target.value, preserve_database_auth_token: false }))} /><button className="login-button" disabled={busy} onClick={() => void test("database")}>{databaseValidation === "testing" ? "Testing…" : "Test Connection"}</button>{status && <p>{status}</p>}{navigation(dbReady)}</>}
    {step === 2 && <><h1>Language Model</h1><fieldset className="provider-choices"><legend>Provider</legend>{PROVIDERS.map((provider) => <label key={provider.id}><input type="radio" checked={draft.llm_provider === provider.id} onChange={() => setDraft((current) => ({ ...current, llm_provider: provider.id }))} /> {provider.label}</label>)}</fieldset><label>Model<input aria-label="Model" value={activeModel} maxLength={200} onChange={(event) => updateProviderValue("models", event.target.value)} /></label><p className="workspace-muted">Enter a model ID available to your API account.</p><label>API Key<input type="password" placeholder={preserveActiveKey ? "Configured — leave blank to keep" : `${providerDefinition(draft.llm_provider).label} API Key`} value={activeApiKey} onChange={(event) => updateProviderValue("apiKeys", event.target.value)} /></label><button className="login-button" disabled={busy || !modelValid(activeModel)} onClick={() => void test("llm")}>{llmValidation === "testing" ? "Testing…" : "Test Connection"}</button>{status && <p>{status}</p>}{navigation(llmReady && modelValid(activeModel))}</>}
    {step === 3 && <><h1>Persona Setup</h1><label>Your display name<input placeholder="Your display name" maxLength={80} value={draft.user_display_name} onChange={(event) => update("user_display_name", event.target.value)} /></label><label>Persona name<input placeholder="Persona name" maxLength={80} value={draft.persona_display_name} onChange={(event) => update("persona_display_name", event.target.value)} /></label><p>Identity starts from the generic template. You can edit its managed text file after setup.</p><input type="file" accept="text/plain,.txt" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 64 * 1024) { setStatus("Identity files must be under 64 KB."); return; } try { setIdentity(await file.text()); setDraft((current) => ({ ...current, preserve_identity: false })); setStatus("Identity file imported."); } catch { setStatus("Identity files must be UTF-8 plain text."); } }} />{status && <p>{status}</p>}{navigation(userNameValid(draft.user_display_name) && personaValid(draft.persona_display_name) && (draft.preserve_identity || identity.trim().length > 0))}</>}
    {step === 4 && <><h1>Review / Initialize</h1><p>Database: Configured</p><p>Language Model: {providerDefinition(draft.llm_provider).label} · {activeModel}</p><p>User: {draft.user_display_name}</p><p>Persona: {draft.persona_display_name}</p><p>Tokens and API keys are never shown here.</p><p>Configuration and identity edits take effect after restarting MindCore.</p>{status && <p>{status}</p>}<div className="setup-navigation"><button className="login-button" onClick={previous}>Back</button><button className="login-button" disabled={busy} onClick={() => void initialize()}>Initialize MindCore</button></div></>}
  </div></main>;
}
